CREATE TABLE person (
    id UUID NOT NULL PRIMARY KEY,
    firstName VARCHAR(100) NOT NULL,
    lastName VARCHAR(100) NOT NULL,
    email   VARCHAR(100) NOT NULL,
    password VARCHAR(100) NOT NULL
)